version: '3.4'

services:
  urlshortener:
    image: ${DOCKER_REGISTRY-}urlshortener
    build:
      context: .
      dockerfile: UrlShortener/Dockerfile
    ports:
    - "5001:443"

  urlshortener-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: UrlShortener.Db
    volumes:
        - ./.containers/database:/var/opt/mssql/data
    ports:
        - "1433:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "StrongPassword123!"