version: '3.4'

services:
 sqldata:
    container_name: sql-server-_dbContext
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=StrongPassword123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

 urlshortener:
    image: yehorlesnevych/urlshortener:latest
    build:
      context: .
      dockerfile: UrlShortener/Dockerfile
    environment:
        "ASPNETCORE_Kestrel__Certificates__Default__Password": "StrongPassword123!"
        "ASPNETCORE_Kestrel__Certificates__Default__Path": "../https/aspnetapp.pfx"
    ports:
       - "5000:8080"
       - "5001:8081"
    restart: 
        always
    volumes:
        - ~/.aspnet/https:/https
    depends_on:
      - sqldata

 redis:
    image: redis:latest
    ports:
    - "6379:6379"
    container_name: redis